### ISSUE TITLE
Illegal symbols (&, space) for class name

### ISSUE THREAD

**Issue by Shine226** [fairnessforensics/wiggum#147]

**Comment by brownsarahm** [comment]
I see you pushed a solution to this, can you add more detail to how and why it happened so that we can check that the solution is robust?

**Comment by Shine226** [comment]
I tested on the dataset having a group called "R&D", after clicking the cell for this group, get an error "SyntaxError: The string did not match the expected pattern."

**Comment by Shine226** [comment]
The error occurs on this line code (subgroup: R&D):
d3.selectAll('.sel-' + subgroup).transition().style('opacity', 1);

**Comment by brownsarahm** [comment]
and your solution is to switch `&` to `_`? 

If it's possible, it would be better to escape the characters and display as provided. 

Also, before we merge this, find the full disallowed list of characters and be sure to handle all of them

**Comment by Shine226** [comment]
I add more invalid characters to the regular expression and escape those characters. For space ' ', just replace space with '_'. These characters will be displayed as provided, only class names for the components will be replaced with '_' if there is a space in the name. I pushed the new code.
