### ISSUE TITLE
Scatterplot not showing correctly after switch from different trend types

### ISSUE THREAD

**Issue by Shine226** [fairnessforensics/wiggum#148]
Click lin_reg cell, next click rank_trend, then click a pearson cell, got a messy scatterplot.
Testing on wages_gender_rank_time_regression2 dataset

**Comment by brownsarahm** [comment]
This happens on multiple data sets, any time a scatter plot detail view is requested after line plot detail view

**Comment by Shine226** [comment]
Are there any other datasets having both rank trend and regression trend that I can use to test and debug on a small size dataset?
