### ISSUE TITLE
Unable to modify settings after uploading folder, "Choosing files"

### ISSUE THREAD

**Issue by darbycobb** [fairnessforensics/wiggum#184]
I have run into an issue where if I upload a folder using "Choose files", when I modify any settings, ie. change variable from binary to categorical, the settings are not saved when you go to visualize it. Wiggum will only display the results from the saved result_df. There is no way to modify the settings of any 'saved' project. For example, the irisres dataset still tries to display Pearson, even when you deselect it from the menu.

**Comment by brownsarahm** [comment]
@darbycobb is this resolved?

**Comment by darbycobb** [comment]
yes! I just double checked

**Comment by brownsarahm** [comment]
thanks!
